# Generated by Django 6.0.2 on 2026-03-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='pincode',
            options={'verbose_name_plural': 'Pincodes'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('father_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('aadhaar_number', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('vid_number', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pincode')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
            options={
                'verbose_name_plural': 'User Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
