# Generated by Django 6.0.2 on 2026-03-31 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gender_options_alter_pincode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pincode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.RenameField(
            model_name='pincode',
            old_name='pin',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='vid_number',
        ),
        migrations.AddField(
            model_name='pincode',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pincode',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='pan_number',
            field=models.CharField(default='Unknown', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='aadhaar_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
