# Generated by Django 6.0.2 on 2026-04-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gender_options_alter_pincode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
